### ISSUE TITLE
devstack 主机重启出现的问题

### ISSUE THREAD

**Issue by boxrice007** [zqfan/openstack#1]
装完devstack后，重启设备，发现网络不通，而且不能上外网，这是什么原因造成？网上有人说运行rejonin_stack.sh这个脚本就OK了，可是我从git克隆下面的项目没有这个脚本。还希望你能帮我看看。谢谢

**Comment by zqfan** [comment]
这个脚本的作用是重新启动各项服务，但是后来被删除了，现在你应该使用`screen -c stack-screenrc`命令来重启各项服务
